version: "3.3"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.deadnode.address=:8090"
      - "--tracing.jaeger=true"
      - "--tracing.jaeger.localAgentHostPort=jaeger:6831"
      - "--accesslog=true"
    ports:
      - "8090:8090"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  deadnode:
    build: .
    ports:
      - "80"
    labels:      
      - "traefik.enable=true"
      - "traefik.http.routers.deadnode.rule=Host(`127.0.0.1`)"
      - "traefik.http.routers.deadnode.entrypoints=deadnode"      